class GoalNotFoundError(Exception):
    pass


class TraceError(Exception):
    pass
